# Generated by Django 2.2.3 on 2019-07-19 07:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('product', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price', models.FloatField()),
                ('date_published', models.DateTimeField(default=datetime.datetime.now)),
                ('date_expiry', models.DateTimeField(blank=True, null=True)),
                ('date_tracked', models.DateTimeField(blank=True, null=True)),
                ('is_claimed', models.BooleanField(default=False)),
            ],
        ),
    ]
